Mandar reporte de tests

diff --git a/ci-taller-demo/Jenkinsfile b/ci-taller-demo/Jenkinsfile
--- a/ci-taller-demo/Jenkinsfile
+++ b/ci-taller-demo/Jenkinsfile
@@ -66,6 +66,29 @@ pipeline {
             }
         }
 
+        always {
+                junit 'ci-taller-demo/target/surefire-reports/*.xml'
+
+                script {
+                    def result = sh(script: '''
+                        PASSED=0
+                        FAILED=0
+                        SKIPPED=0
+
+                        for file in ci-taller-demo/target/surefire-reports/*.xml; do
+                            [ -f "$file" ] || continue
+                            PASSED=$((PASSED + $(grep -o 'testsuite.*tests="\\?\\([0-9]\\+\\)"' "$file" | sed -E 's/.*tests="([0-9]+)".*/\\1/')))
+                            FAILED=$((FAILED + $(grep -o 'failures="\\?\\([0-9]\\+\\)"' "$file" | sed -E 's/.*failures="([0-9]+)".*/\\1/')))
+                            SKIPPED=$((SKIPPED + $(grep -o 'skipped="\\?\\([0-9]\\+\\)"' "$file" | sed -E 's/.*skipped="([0-9]+)".*/\\1/')))
+                        done
+
+                        echo "Tests: $PASSED, Fallos: $FAILED, Saltados: $SKIPPED"
+                    ''', returnStdout: true).trim()
+
+                    env.TEST_RESULT_MESSAGE = result
+                }
+            }
+
      post {
         success {
                 withCredentials([
@@ -75,7 +98,7 @@ pipeline {
                     sh """
                     curl -s -X POST "https://api.telegram.org/bot${BOT_TOKEN}/sendMessage" \\
                     -d chat_id=${CHAT_ID} \\
-                    -d text="✅ Éxito: Pipeline completado correctamente en Jenkins."
+                    -d text="✅ Éxito: Pipeline completado correctamente en Jenkins. \\n📊 ${TEST_RESULT_MESSAGE}"
                 """
             }
         }
@@ -88,7 +111,7 @@ pipeline {
                     sh """
                     curl -s -X POST "https://api.telegram.org/bot${BOT_TOKEN}/sendMessage" \\
                     -d chat_id=${CHAT_ID} \\
-                    -d text="❌ Error: Falló el pipeline en Jenkins. Revisar logs."
+                    -d text="❌ Error: Falló el pipeline en Jenkins. Revisar logs. \\n📊 ${TEST_RESULT_MESSAGE}"
                 """
             }
         }
